# -------------------------------------------------
# Netlify 配置（UTF?8 without BOM，纯 TOML）
# -------------------------------------------------

[build]
  # 站点构建命令（这里使用上面 package.json 的占位脚本）
  command   = "npm run build"
  # 构建完成后要发布的目录
  publish   = "public"
  # 函数代码所在目录（可省略，因为默认就是 functions）
  functions = "functions"

[functions]
  directory = "functions"

# -------------------------------------------------
# 受保护区域（role?based redirect）
# -------------------------------------------------
[[redirects]]
  from       = "/protected/*"
  status     = 200                # 直接返回文件（如果有角色的话）
  force      = true
  conditions = { Role = ["member"] }

# 未登录时把请求转到登录页面（用 redirect 函数保留原始路径）
[[redirects]]
  from   = "/protected/*"
  to     = "/.netlify/functions/redirect"
  status = 200
  force  = true
